require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/examples", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Example. As you add validations to Example, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Example.create! valid_attributes
      get examples_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      example = Example.create! valid_attributes
      get example_url(example)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_example_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      example = Example.create! valid_attributes
      get edit_example_url(example)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Example" do
        expect {
          post examples_url, params: { example: valid_attributes }
        }.to change(Example, :count).by(1)
      end

      it "redirects to the created example" do
        post examples_url, params: { example: valid_attributes }
        expect(response).to redirect_to(example_url(Example.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Example" do
        expect {
          post examples_url, params: { example: invalid_attributes }
        }.to change(Example, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post examples_url, params: { example: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested example" do
        example = Example.create! valid_attributes
        patch example_url(example), params: { example: new_attributes }
        example.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the example" do
        example = Example.create! valid_attributes
        patch example_url(example), params: { example: new_attributes }
        example.reload
        expect(response).to redirect_to(example_url(example))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        example = Example.create! valid_attributes
        patch example_url(example), params: { example: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested example" do
      example = Example.create! valid_attributes
      expect {
        delete example_url(example)
      }.to change(Example, :count).by(-1)
    end

    it "redirects to the examples list" do
      example = Example.create! valid_attributes
      delete example_url(example)
      expect(response).to redirect_to(examples_url)
    end
  end
end
