# Generated by Django 4.1.1 on 2023-01-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due', models.DateTimeField()),
                ('fromwho', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='polls.status', verbose_name='状況')),
            ],
        ),
    ]
