# Generated by Django 4.1.1 on 2023-01-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
