default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: rails_example_development

test:
  <<: *default
  database: rails_example_test

production:
  <<: *default
  host: database-2.cluster-cgklnrcdw5xr.ap-northeast-1.rds.amazonaws.com
  username: admin
  database: rails_example_production
  password: D4y903jgkgdajx3rk3

