default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: rails_example_development

test:
  <<: *default
  database: rails_example_test
