# Generated by Django 4.1.1 on 2022-12-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='article_title',
        ),
    ]
