# Generated by Django 4.1.1 on 2022-12-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_article_text_article_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=models.TextField(default=''),
        ),
    ]
