require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/exes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Ex. As you add validations to Ex, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ex.create! valid_attributes
      get exes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ex = Ex.create! valid_attributes
      get ex_url(ex)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ex_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      ex = Ex.create! valid_attributes
      get edit_ex_url(ex)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ex" do
        expect {
          post exes_url, params: { ex: valid_attributes }
        }.to change(Ex, :count).by(1)
      end

      it "redirects to the created ex" do
        post exes_url, params: { ex: valid_attributes }
        expect(response).to redirect_to(ex_url(Ex.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ex" do
        expect {
          post exes_url, params: { ex: invalid_attributes }
        }.to change(Ex, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post exes_url, params: { ex: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ex" do
        ex = Ex.create! valid_attributes
        patch ex_url(ex), params: { ex: new_attributes }
        ex.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ex" do
        ex = Ex.create! valid_attributes
        patch ex_url(ex), params: { ex: new_attributes }
        ex.reload
        expect(response).to redirect_to(ex_url(ex))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        ex = Ex.create! valid_attributes
        patch ex_url(ex), params: { ex: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ex" do
      ex = Ex.create! valid_attributes
      expect {
        delete ex_url(ex)
      }.to change(Ex, :count).by(-1)
    end

    it "redirects to the exes list" do
      ex = Ex.create! valid_attributes
      delete ex_url(ex)
      expect(response).to redirect_to(exes_url)
    end
  end
end
